FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY runner/ ./runner

CMD ["python", "runner/runner.py", "--project-dir", "/app/project", "--port", "8000", "--web-port", "8080"]